# Art
famous_paintings = [
    "Josef Albers: Homage to the Square: Against Deep Blue (1955)",
    "Albrecht Altdorfer: The Battle of Alexander at Issus (1528–29)",
    "Giuseppe Arcimboldo: Fire (1566)",
    "Hendrick Avercamp: Winter Scene on a Canal (c 1630)",
    "Francis Bacon: Three Studies for Figures at the Base of a Crucifixion (1944)",
    "Hans Baldung Grien: Death and the Maiden (1517)",
    "Giacomo Balla: Abstract Speed + Sound (1913–14)",
    "Georg Baselitz: Allegory of Art",
    "Georg Baselitz: The Great Friends (1965)",
    "Max Beckmann: Actors - Triptych (1941–42)",
    "Giovanni Bellini: Prayer of Christ in the Garden of Gethsemane (c 1465)",
    "Frits Van den Berghe: Sunday (1924)",
    "Umberto Boccioni: The Farewells (1911)",
    "Arnold Böcklin: Spring Awakening (1880)",
    "Pierre Bonnard: Backlit Nude (1908)",
    "Hieronymus Bosch: The Garden of Earthly Delights (c 1500)",
    "Sandro Botticelli: The Birth of Venus (1478–1487)",
    "François Boucher: The Blonde Odalisque (1751)",
    "Georges Braque: The Female Musician (1917–1918)",
    "Pieter Brueghel the Elder: Landscape with the Fall of Icarus (c 1550)",
    "Pieter Brueghel the Elder: The Triumph of Death",
    "Pieter Brueghel the Elder: The Hunters in the Snow (Return of the Hunters) (1565)",
    "Gustave Caillebotte: Parisian Street, Rainy Day (1877)",
    "Antonio Canaletto: Return of the Bucintoro to the Molo on Ascension Day (1734)",
    "Caravaggio: Supper at Emmaus (1596–1598)",
    "Caravaggio: The Lute Player (c 1596)",
    "Vittore Carpaccio: Miracle of the Relic of the Cross at the Ponte di Rialto (1494)",
    "Annibale Carracci: River Landscape (c 1595)",
    "Mary Cassatt: The Child's Bath (c 1891)",
    "Paul Cézanne: Mont Sainte-Victoire (1897)",
    "Paul Cézanne: Bathers (c 1900)",
    "Marc Chagall: I and the Village (1911)",
    "Jean Siméon Chardin: The Young Schoolmistress (before 1740)",
    "China: Clear Weather in the Valley (12th century)",
    "John Constable: Salisbury Cathedral (1823)",
    "Lovis Corinth: Self-portrait in Front of the Easel (1914)",
    "Correggio: Leda and the Swan (c 1530)",
    "Gustave Courbet: Breakfast at the Hunt (1858)",
    "Lucas Cranach the Elder: Adam and Eve in Paradise (1531)",
    "Salvador Dalí: The Burning Giraffe (1936)",
    "Honoré Daumier: Ecce Homo (c 1849–1852)",
    "Jacques-Louis David: The Lictors Bring to Brutus the Bodies of His Sons (1789)",
    "Edgar Degas: Woman in a Tub (1886)",
    "Eugène Delacroix: The Massacre at Chios (1824)",
    "Robert Delaunay: Eiffel Tower, Champs de Mars (1911)",
    "Sonia Delaunay-Terk: Electric Prisms (1914)",
    "Niklaus Manuel Deutsch: Pyramus and Thisbe (after 1523)",
    "Otto Dix: Flanders (1934–1936)",
    "Jean Dubuffet: Prosperous country (1944)",
    "Duccio: Christ Healing a Blind Man (1308–1310)",
    "Marcel Duchamp: Sad Young Man in a Train (1911)",
    "Albrecht Dürer: Picture of a Young Venetian Woman (1505)",
    "Albrecht Dürer: Self-portrait (1498)",
    "Anthony van Dyck: Samson and Delilah (c 1628–1630)",
    "Thomas Eakins: Max Schmitt in a Single Scull (1871)",
    "James Ensor: Self-portrait with Masks (1899)",
    "Max Ernst: The Attirement of the Bride (1939)",
    "Jan van Eyck: The Madonna of the Chancellor Rolin (1434)",
    "Lyonel Feininger: Bird Cloud (1926)",
    "Lucio Fontana: Concetto Spaziale (1957)",
    "Piero della Francesca: Resurrection of Christ (c 1460)",
    "Piero della Francesca: The Birth of Christ (around 1480)",
    "Helen Frankenthaler: Mountains and Sea (1952)",
    "Caspar David Friedrich: The Sea of Ice (1822–1824)",
    "Henry Fuseli: Titania Caressing Bottom with a Donkey's Head (1793)",
    "Thomas Gainsborough: Mr and Mrs Andrews (1748–1749)",
    "Paul Gauguin: Mahana no atua (Day of the God) (1894)",
    "Théodore Géricault: The Raft of the Medusa (1819)",
    "Alberto Giacometti: Portrait of Jean Genet (1955)",
    "Giorgione: Sleeping Venus (1508)",
    "Giorgione or Titian: Pastoral Concert (c 1510)",
    "Giotto: The Mourning of Christ (c 1304–1306)",
    "Hugo van der Goes: Adoration of the Kings (around 1470)",
    "Vincent van Gogh: Self-portrait (1889)",
    "Vincent van Gogh: Café Terrace at Night (1888)",
    "Arshile Gorky: One Year the Milkweed (1944)",
    "Francisco de Goya: The Colossus (attribution uncertain)",
    "Francisco de Goya: The Naked Maja (c 1800)",
    "Francisco de Goya: Carnival Scene (1793)",
    "Benozzo Gozzoli: The Procession of the Magi (c 1460)",
    "Gotthard Graubner: Black Skin (1969)",
    "El Greco: The Burial of the Count of Orgaz (1586)",
    "El Greco: View of Toledo (1600–1610)",
    "Juan Gris: The Breakfast Table (1915)",
    "George Grosz: Untitled (1920)",
    "Matthias Grünewald: Crucifixion from the Isenheim Altarpiece (1515)",
    "Erich Heckel: Convalescing Woman (1912–1913)",
    "Hannah Höch: Cut with the Kitchen Knife (1919–1920)",
    "Ferdinand Hodler: Youth Admired by the Woman (1903)",
    "Hans Holbein the Younger: Portrait of the Artist's Family (Holbein) (1528)",
    "Winslow Homer: The Fox Hunt (1893)",
    "Edward Hopper: Nighthawks (1942)",
    "William Holman Hunt: The Hireling Shepherd (1851)",
    "Jean Auguste Dominique Ingres: The Turkish Bath (1862)",
    "Johannes Itten: The Encounter (1916)",
    "Geertgen tot Sint Jans: John the Baptist in the Wilderness (c 1485–1490)",
    "Alexej von Jawlensky: Meditation (1918)",
    "Jasper Johns: Flag (1954–1955)",
    "Wassily Kandinsky: Improvisation 6 (1910)",
    "Kangra School: Radha and Krishna in the Garden (c 1780)",
    "Wilhelm von Kaulbach: Titus Destroying Jerusalem (1846)",
    "Fernand Khnopff: Caress of the Sphinx (1896)",
    "Ernst Ludwig Kirchner: Five Women on the Street (1913)",
    "Konrad Klapheck: The War (1965)",
    "Paul Klee: Bird Garden (1924)",
    "Franz Kline: C & O (1958)",
    "Wilhelm von Kobell: The Siege of Kosel (1808)",
    "Oskar Kokoschka: The Bride of the Wind (1914)",
    "Jan Kupecky: Portrait of the Miniaturist Karl Bruni (1709)",
    "Fernand Léger: The Wedding (1911)",
    "Wilhelm Leibl: Three Women in Church (1878–1882)",
    "Franz von Lenbach: Franz von Lenbach with Wife and Daughters (1903)",
    "Roy Lichtenstein: Girl with Hair Band (1965)",
    "Max Liebermann: Women Mending Nets (1887–1889)",
    "Richard Lindner: The Meeting (1953)",
    "Stefan Lochner: Madonna of the Rose Bower (c 1448)",
    "Lorenzo Lotto: The Sleeping Child Jesus with the Madonna, St Joseph and St. Catherine of Alexandria (c. 1533)",
    "Morris Louis: Beta-Kappa (1961)",
    "August Macke: Woman with Umbrella in Front of a Hat Shop (1914)",
    "René Magritte: The Empire of Light (1954)",
    "Kazimir Malevich: An Englishman in Moscow (1914)",
    "Édouard Manet: Olympia (1863)",
    "Andrea Mantegna: The Crucifixion (1457–1460)",
    "Franz Marc: The Tiger (1912)",
    "Hans von Marées: Golden Age (1879–1885)",
    "Reginald Marsh: Twenty Cent Movie (1936)",
    "Masaccio: The Tribute Money (c 1425)",
    "Jan Matsys: Flora (1559)",
    "Henri Matisse: Bather at the River (1916–1917)",
    "Henri Matisse: Blue Nude (1907)",
    "William McTaggart: The Storm (1890)",
    "Hans Memling: St John's Altarpiece (before 1494)",
    "Adolph von Menzel: The Flute Concert (1850–1852)",
    "Jean Metzinger: The Racing Cyclist (1914)",
    "John Everett Millais: Ophelia (1851–1852)",
    "Joan Miró: Dutch Interior I (1928)",
    "László Moholy-Nagy: LIS (1922)",
    "Claude Monet: Woman in a Garden (1867)",
    "Piet Mondrian: Apple Tree in Bloom (1912)",
    "Edvard Munch: Ashes (1894–95)",
    "Edvard Munch: Four Girls on the Bridge (1905)",
    "Gabriele Münter: Village Street in Winter (1911)",
    "Bartolomé Esteban Murillo: Rest on the Flight into Egypt (c1665)",
    "Louis or Antoine Le Nain: Peasant Family in an Interior (1640–1645)",
    "Paul Nash: Dream Landscape (1936–1938)",
    "Ernst Wilhelm Nay: Grauzug (1960)",
    "Mikhail Nesterov: The Great Consecration (1897–98)",
    "Emil Nolde: St Mary of Egypt (1912)",
    "Georgia O'Keeffe: White Calico Flower (1931)",
    "Richard Oelze: Daily Stress (1934)",
    "Victor Pasmore: Inland Coastal Landscape (1950)",
    "Joachim Patinir: The Baptism of Christ (c 1515)",
    "Constant Permeke: The Engaged Couple",
    "Francis Picabia: Very Rare Picture of Earth (1915)",
    "Pablo Picasso: Guernica (1937)",
    "Pablo Picasso: La Vie (1903–1904)",
    "Jackson Pollock: Autumn Rhythm (1950)",
    "Nicolas Poussin: The Adoration of the Golden Calf (1635)",
    "Nicolas Poussin: Sleeping Venus and Cupid (1630)",
    "Henry Raeburn: Rev Robert Walker Skating (1784)",
    "Raphael: Madonna of the Meadow (1506)",
    "Arnulf Rainer: Self-portrait Overpainted (1962–1963)",
    "Rembrandt: The Jewish Bride (1666)",
    "Rembrandt: Self-portrait as Paul (1661)",
    "Auguste Renoir: Luncheon of the Boating Party (1880)",
    "Ilya Repin: Reply of the Zaporozhian Cossacks to Sultan Mehmed IV of Turkey (1880–1891)",
    "Sebastiano Ricci: Bathsheba at her Bath (c 1720)",
    "Hyacinthe Rigaud: Portrait of Louis XIV (1701)",
    "Hubert Robert: Design for the Arrangement of the Great Gallery of the Louvre des Louvre (1796)",
    "Giulio Romano: Virgin and Child and the Young John (c 1518)",
    "Mark Rothko: Red, Brown and Black (1958)",
    "Carl Rottmann: From the Greek Cycle (1838–1850)",
    "Henri Rousseau: The Sleeping Gypsy (1897)",
    "Peter Paul Rubens: Château de Steen with Hunter (c 1635–1637)",
    "Peter Paul Rubens: Mercury and Argus (1638)",
    "Jacob Isaakszoon van Ruisdael: The Large Forest (c 1655–1660)",
    "Philipp Otto Runge: The Hülsenbeck Children (1805–1806)",
    "Pieter Saenredam: Interior of Grote Kerk in Haarlem (1648)",
    "Egon Schiele: Mother with Two Children (1915–1917)",
    "Karl Friedrich Schinkel: Medieval City on a River (1815)",
    "Oskar Schlemmer: Group on the Railings I (1931)",
    "Kurt Schwitters: Merzbild 25A, Constellation (1920)",
    "Georges Seurat: Sunday Afternoon on the Island of La Grande Jatte (1884–1886)",
    "Luca Signorelli: Portrait of an Older Man (c 1500)",
    "Tawaraya Sōtatsu: Waves of Matsushima (c 1630)",
    "Stanley Spencer: The Resurrection, Cookham (1924–1927)",
    "Carl Spitzweg: The Poor Poet (1839)",
    "George Stubbs: The Grosvenor Hunt (1762)",
    "Franz von Stuck: Salome (1906)",
    "Yves Tanguy: About Four o'clock in the Summer, the Hope (1929)",
    "Giovanni Battista Tiepolo: Virtue and Nobility putting Ignorance to Flight (c 1745)",
    "Jacopo Tintoretto: Bacchus, with Ariadne Crowned by Venus (1576–77)",
    "Titian: Bacchanals (1523–1526)",
    "Titian: Diana and Callisto (1556–1559)",
    "Georges de La Tour: The Dream of St Joseph (c. 1628–1645)",
    "Georges de La Tour: The Fortune Teller (c 1620–1621)",
    "William Turner: The Burning of the Houses of Parliament (1834–1835)",
    "William Turner: Venice - La Dogana and Santa Maria della Salute (1843)",
    "Paolo Uccello: The Battle of San Romano (c 1456)",
    "Emilio Vedova: Picture of Time – Barrier (1951)",
    "Diego Velázquez: Las Meninas (1656)",
    "Diego Velázquez: Prince Balthasar Carlos (1635)",
    "Diego Velázquez: The Surrender of Breda (1634)",
    "Josef Albers: Homage to the Square: Against Deep Blue (1955)",
    "Albrecht Altdorfer: The Battle of Alexander at Issus (1528–29)",
    "Giuseppe Arcimboldo: Fire (1566)",
    "Hendrick Avercamp: Winter Scene on a Canal (c 1630)",
    "Francis Bacon: Three Studies for Figures at the Base of a Crucifixion (1944)",
    "Hans Baldung Grien: Death and the Maiden (1517)",
    "Giacomo Balla: Abstract Speed + Sound (1913–14)",
    "Georg Baselitz: Allegory of Art",
    "Georg Baselitz: The Great Friends (1965)",
    "Max Beckmann: Actors - Triptych (1941–42)",
    "Giovanni Bellini: Prayer of Christ in the Garden of Gethsemane (c 1465)",
    "Frits Van den Berghe: Sunday (1924)",
    "Umberto Boccioni: The Farewells (1911)",
    "Arnold Böcklin: Spring Awakening (1880)",
    "Pierre Bonnard: Backlit Nude (1908)",
    "Hieronymus Bosch: The Garden of Earthly Delights (c 1500)",
    "Sandro Botticelli: The Birth of Venus (1478–1487)",
    "François Boucher: The Blonde Odalisque (1751)",
    "Georges Braque: The Female Musician (1917–1918)",
    "Pieter Brueghel the Elder: Landscape with the Fall of Icarus (c 1550)",
    "Pieter Brueghel the Elder: The Triumph of Death",
    "Pieter Brueghel the Elder: The Hunters in the Snow (Return of the Hunters) (1565)",
    "Gustave Caillebotte: Parisian Street, Rainy Day (1877)",
    "Antonio Canaletto: Return of the Bucintoro to the Molo on Ascension Day (1734)",
    "Caravaggio: Supper at Emmaus (1596–1598)",
    "Caravaggio: The Lute Player (c 1596)",
    "Vittore Carpaccio: Miracle of the Relic of the Cross at the Ponte di Rialto (1494)",
    "Annibale Carracci: River Landscape (c 1595)",
    "Mary Cassatt: The Child's Bath (c 1891)",
    "Paul Cézanne: Mont Sainte-Victoire (1897)",
    "Paul Cézanne: Bathers (c 1900)",
    "Marc Chagall: I and the Village (1911)",
    "Jean Siméon Chardin: The Young Schoolmistress (before 1740)",
    "China: Clear Weather in the Valley (12th century)",
    "John Constable: Salisbury Cathedral (1823)",
    "Lovis Corinth: Self-portrait in Front of the Easel (1914)",
    "Correggio: Leda and the Swan (c 1530)",
    "Gustave Courbet: Breakfast at the Hunt (1858)",
    "Lucas Cranach the Elder: Adam and Eve in Paradise (1531)",
    "Salvador Dalí: The Burning Giraffe (1936)",
    "Honoré Daumier: Ecce Homo (c 1849–1852)",
    "Jacques-Louis David: The Lictors Bring to Brutus the Bodies of His Sons (1789)",
    "Edgar Degas: Woman in a Tub (1886)",
    "Eugène Delacroix: The Massacre at Chios (1824)",
    "Robert Delaunay: Eiffel Tower, Champs de Mars (1911)",
    "Sonia Delaunay-Terk: Electric Prisms (1914)",
    "Niklaus Manuel Deutsch: Pyramus and Thisbe (after 1523)",
    "Otto Dix: Flanders (1934–1936)",
    "Jean Dubuffet: Prosperous country (1944)",
    "Duccio: Christ Healing a Blind Man (1308–1310)",
    "Marcel Duchamp: Sad Young Man in a Train (1911)",
    "Albrecht Dürer: Picture of a Young Venetian Woman (1505)",
    "Albrecht Dürer: Self-portrait (1498)",
    "Anthony van Dyck: Samson and Delilah (c 1628–1630)",
    "Thomas Eakins: Max Schmitt in a Single Scull (1871)",
    "James Ensor: Self-portrait with Masks (1899)",
    "Max Ernst: The Attirement of the Bride (1939)",
    "Jan van Eyck: The Madonna of the Chancellor Rolin (1434)",
    "Lyonel Feininger: Bird Cloud (1926)",
    "Lucio Fontana: Concetto Spaziale (1957)",
    "Piero della Francesca: Resurrection of Christ (c 1460)",
    "Piero della Francesca: The Birth of Christ (around 1480)",
    "Helen Frankenthaler: Mountains and Sea (1952)",
    "Caspar David Friedrich: The Sea of Ice (1822–1824)",
    "Henry Fuseli: Titania Caressing Bottom with a Donkey's Head (1793)",
    "Thomas Gainsborough: Mr and Mrs Andrews (1748–1749)",
    "Paul Gauguin: Mahana no atua (Day of the God) (1894)",
    "Théodore Géricault: The Raft of the Medusa (1819)",
    "Alberto Giacometti: Portrait of Jean Genet (1955)",
    "Giorgione: Sleeping Venus (1508)",
    "Giorgione or Titian: Pastoral Concert (c 1510)",
    "Giotto: The Mourning of Christ (c 1304–1306)",
    "Hugo van der Goes: Adoration of the Kings (around 1470)",
    "Vincent van Gogh: Self-portrait (1889)",
    "Vincent van Gogh: Café Terrace at Night (1888)",
    "Arshile Gorky: One Year the Milkweed (1944)",
    "Francisco de Goya: The Colossus (attribution uncertain)",
    "Francisco de Goya: The Naked Maja (c 1800)",
    "Francisco de Goya: Carnival Scene (1793)",
    "Benozzo Gozzoli: The Procession of the Magi (c 1460)",
    "Gotthard Graubner: Black Skin (1969)",
    "El Greco: The Burial of the Count of Orgaz (1586)",
    "El Greco: View of Toledo (1600–1610)",
    "Juan Gris: The Breakfast Table (1915)",
    "George Grosz: Untitled (1920)",
    "Matthias Grünewald: Crucifixion from the Isenheim Altarpiece (1515)",
    "Erich Heckel: Convalescing Woman (1912–1913)",
    "Hannah Höch: Cut with the Kitchen Knife (1919–1920)",
    "Ferdinand Hodler: Youth Admired by the Woman (1903)",
    "Hans Holbein the Younger: Portrait of the Artist's Family (Holbein) (1528)",
    "Winslow Homer: The Fox Hunt (1893)",
    "Edward Hopper: Nighthawks (1942)",
    "William Holman Hunt: The Hireling Shepherd (1851)",
    "Jean Auguste Dominique Ingres: The Turkish Bath (1862)",
    "Johannes Itten: The Encounter (1916)",
    "Geertgen tot Sint Jans: John the Baptist in the Wilderness (c 1485–1490)",
    "Alexej von Jawlensky: Meditation (1918)",
    "Jasper Johns: Flag (1954–1955)",
    "Wassily Kandinsky: Improvisation 6 (1910)",
    "Kangra School: Radha and Krishna in the Garden (c 1780)",
    "Wilhelm von Kaulbach: Titus Destroying Jerusalem (1846)",
    "Fernand Khnopff: Caress of the Sphinx (1896)",
    "Ernst Ludwig Kirchner: Five Women on the Street (1913)",
    "Konrad Klapheck: The War (1965)",
    "Paul Klee: Bird Garden (1924)",
    "Franz Kline: C & O (1958)",
    "Wilhelm von Kobell: The Siege of Kosel (1808)",
    "Oskar Kokoschka: The Bride of the Wind (1914)",
    "Jan Kupecky: Portrait of the Miniaturist Karl Bruni (1709)",
    "Fernand Léger: The Wedding (1911)",
    "Wilhelm Leibl: Three Women in Church (1878–1882)",
    "Franz von Lenbach: Franz von Lenbach with Wife and Daughters (1903)",
    "Roy Lichtenstein: Girl with Hair Band (1965)",
    "Max Liebermann: Women Mending Nets (1887–1889)",
    "Richard Lindner: The Meeting (1953)",
    "Stefan Lochner: Madonna of the Rose Bower (c 1448)",
    "Lorenzo Lotto: The Sleeping Child Jesus with the Madonna, St Joseph and St. Catherine of Alexandria (c. 1533)",
    "Morris Louis: Beta-Kappa (1961)",
    "August Macke: Woman with Umbrella in Front of a Hat Shop (1914)",
    "René Magritte: The Empire of Light (1954)",
    "Kazimir Malevich: An Englishman in Moscow (1914)",
    "Édouard Manet: Olympia (1863)",
    "Andrea Mantegna: The Crucifixion (1457–1460)",
    "Franz Marc: The Tiger (1912)",
    "Hans von Marées: Golden Age (1879–1885)",
    "Reginald Marsh: Twenty Cent Movie (1936)",
    "Masaccio: The Tribute Money (c 1425)",
    "Jan Matsys: Flora (1559)",
    "Henri Matisse: Bather at the River (1916–1917)",
    "Henri Matisse: Blue Nude (1907)",
    "William McTaggart: The Storm (1890)",
    "Hans Memling: St John's Altarpiece (before 1494)",
    "Adolph von Menzel: The Flute Concert (1850–1852)",
    "Jean Metzinger: The Racing Cyclist (1914)",
    "John Everett Millais: Ophelia (1851–1852)",
    "Joan Miró: Dutch Interior I (1928)",
    "László Moholy-Nagy: LIS (1922)",
    "Claude Monet: Woman in a Garden (1867)",
    "Piet Mondrian: Apple Tree in Bloom (1912)",
    "Edvard Munch: Ashes (1894–95)",
    "Edvard Munch: Four Girls on the Bridge (1905)",
    "Gabriele Münter: Village Street in Winter (1911)",
    "Bartolomé Esteban Murillo: Rest on the Flight into Egypt (c1665)",
    "Louis or Antoine Le Nain: Peasant Family in an Interior (1640–1645)",
    "Paul Nash: Dream Landscape (1936–1938)",
    "Ernst Wilhelm Nay: Grauzug (1960)",
    "Mikhail Nesterov: The Great Consecration (1897–98)",
    "Emil Nolde: St Mary of Egypt (1912)",
    "Georgia O'Keeffe: White Calico Flower (1931)",
    "Richard Oelze: Daily Stress (1934)",
    "Victor Pasmore: Inland Coastal Landscape (1950)",
    "Joachim Patinir: The Baptism of Christ (c 1515)",
    "Constant Permeke: The Engaged Couple",
    "Francis Picabia: Very Rare Picture of Earth (1915)",
    "Pablo Picasso: Guernica (1937)",
    "Pablo Picasso: La Vie (1903–1904)",
    "Jackson Pollock: Autumn Rhythm (1950)",
    "Nicolas Poussin: The Adoration of the Golden Calf (1635)",
    "Nicolas Poussin: Sleeping Venus and Cupid (1630)",
    "Henry Raeburn: Rev Robert Walker Skating (1784)",
    "Raphael: Madonna of the Meadow (1506)",
    "Arnulf Rainer: Self-portrait Overpainted (1962–1963)",
    "Rembrandt: The Jewish Bride (1666)",
    "Rembrandt: Self-portrait as Paul (1661)",
    "Auguste Renoir: Luncheon of the Boating Party (1880)",
    "Ilya Repin: Reply of the Zaporozhian Cossacks to Sultan Mehmed IV of Turkey (1880–1891)",
    "Sebastiano Ricci: Bathsheba at her Bath (c 1720)",
    "Hyacinthe Rigaud: Portrait of Louis XIV (1701)",
    "Hubert Robert: Design for the Arrangement of the Great Gallery of the Louvre des Louvre (1796)",
    "Giulio Romano: Virgin and Child and the Young John (c 1518)",
    "Mark Rothko: Red, Brown and Black (1958)",
    "Carl Rottmann: From the Greek Cycle (1838–1850)",
    "Henri Rousseau: The Sleeping Gypsy (1897)",
    "Peter Paul Rubens: Château de Steen with Hunter (c 1635–1637)",
    "Peter Paul Rubens: Mercury and Argus (1638)",
    "Jacob Isaakszoon van Ruisdael: The Large Forest (c 1655–1660)",
    "Philipp Otto Runge: The Hülsenbeck Children (1805–1806)",
    "Pieter Saenredam: Interior of Grote Kerk in Haarlem (1648)",
    "Egon Schiele: Mother with Two Children (1915–1917)",
    "Karl Friedrich Schinkel: Medieval City on a River (1815)",
    "Oskar Schlemmer: Group on the Railings I (1931)",
    "Kurt Schwitters: Merzbild 25A, Constellation (1920)",
    "Georges Seurat: Sunday Afternoon on the Island of La Grande Jatte (1884–1886)",
    "Luca Signorelli: Portrait of an Older Man (c 1500)",
    "Tawaraya Sōtatsu: Waves of Matsushima (c 1630)",
    "Stanley Spencer: The Resurrection, Cookham (1924–1927)",
    "Carl Spitzweg: The Poor Poet (1839)",
    "George Stubbs: The Grosvenor Hunt (1762)",
    "Franz von Stuck: Salome (1906)",
    "Yves Tanguy: About Four o'clock in the Summer, the Hope (1929)",
    "Giovanni Battista Tiepolo: Virtue and Nobility putting Ignorance to Flight (c 1745)",
    "Jacopo Tintoretto: Bacchus, with Ariadne Crowned by Venus (1576–77)",
    "Titian: Bacchanals (1523–1526)",
    "Titian: Diana and Callisto (1556–1559)",
    "Georges de La Tour: The Dream of St Joseph (c. 1628–1645)",
    "Georges de La Tour: The Fortune Teller (c 1620–1621)",
    "William Turner: The Burning of the Houses of Parliament (1834–1835)",
    "William Turner: Venice - La Dogana and Santa Maria della Salute (1843)",
    "Paolo Uccello: The Battle of San Romano (c 1456)",
    "Emilio Vedova: Picture of Time – Barrier (1951)",
    "Diego Velázquez: Las Meninas (1656)",
    "Diego Velázquez: Prince Balthasar Carlos (1635)",
    "Diego Velázquez: The Surrender of Breda (1634)",
    "Jan Vermeer: The Artist in his Atelier (c 1670)",
    "Jan Vermeer: View of Delft (c 1660)",
    "Paolo Veronese: The Wedding at Cana (1562–1563)",
    "Élisabeth Vigée-Lebrun: Self-Portrait with Daughter (1789)",
    "Leonardo da Vinci: The Virgin and Child with St Anne (c. 1510)",
    "Wolf Vostell: Miss America (1968)",
    "Andy Warhol: Texan, Portrait of Robert Rauschenberg (1963)",
    "Antoine Watteau: Pilgrimage to Cythera (1717)",
    "Rogier van der Weyden: Saint Johns Altarpiece (after 1450)",
    "James McNeill Whistler: Nocturne in Black and Gold: The Falling Rocket (1877)",
    "David Wilkie: William Bethune with Wife and Daughter (1804)",
    "Fritz Winter: Composition in Blue (1953)",
    "Konrad Witz: The Knights Abisai, Sibbechai and Benaja Bring King David Water (c 1435)",
    "Grant Wood: American Gothic (1930)",
    "Joseph Wright of Derby: An Experiment on a Bird in the Air Pump (1767–1768)",
    "Andrew Wyeth: Christina's World (1948)",
    "Francisco de Zurbarán: Still Life with Lemons, Oranges and a Rose (1633)",
]

famous_photos = [
    "The Terror Of War, Nick Ut, 1972",
    "The Burning Monk, Malcolm Browne, 1963",
    "Starving Child And Vulture, Kevin Carter, 1993",
    "Lunch Atop A Skyscraper, 1932",
    "Tank Man, Jeff Widener, 1989",
    "Falling Man, Richard Drew, 2001",
    "Alan Kurdi, Nilüfer Demir, 2015",
    "Earthrise, William Anders, NASA, 1968",
    "Mushroom Cloud Over Nagasaki, Lieutenant Charles Levy, 1945",
    "V-J Day In Times Square, Alfred Eisenstaedt, 1945",
    "Pillars Of Creation, Nasa, 1995",
    "Fire Escape Collapse, Stanley Forman, 1975",
    "A Man On The Moon, Neil Armstrong, Nasa, 1969",
    "Albino Boy, Biafra, Don Mccullin, 1969",
    "Jewish Boy Surrenders In Warsaw, 1943",
    "Bloody Saturday, H.s. Wong, 1937",
    "Migrant Mother, Dorothea Lange, 1936",
    "The Hindenburg Disaster, Sam Shere, 1937",
    "Guerillero Heroico, Alberto Korda, 1960",
    "Dalí Atomicus, Philippe Halsman, 1948",
    "View From The Window At Le Gras, Joseph Nicéphore Niépce, 1826",
    "Leap Into Freedom, Peter Leibing, 1961",
    "The Hand Of Mrs. Wilhelm Röntgen, Wilhelm Conrad Röntgen, 1895",
    "Flag Raising On Iwo Jima, Joe Rosenthal, 1945",
    "Emmett Till, David Jackson, 1955",
    "Cotton Mill Girl, Lewis Hine, 1908",
    "Hitler At A Nazi Party Rally, Heinrich Hoffmann, 1934",
    "Gandhi And The Spinning Wheel, Margaret Bourke-White, 1946",
    "Fetus, 18 Weeks, Lennart Nilsson, 1965",
    "D-Day, Robert Capa, 1944",
    "The Pillow Fight, Harry Benson, 1964",
    "The Face Of Aids, Therese Frare, 1990",
    "First Cell-Phone Picture, Philippe Kahn, 1997",
    "Raising A Flag Over The Reichstag, Yevgeny Khaldei, 1945",
    "Behind Closed Doors, Donna Ferrato, 1982",
    "Famine In Somalia, James Nachtwey, 1992",
    "Muhammad Ali Vs. Sonny Liston, Neil Leifer, 1965",
    "The Situation Room, Pete Souza, 2011",
    "Nuit De Noel, Malick Sidibe, 1963",
    "Saigon Execution, Eddie Adams, 1968",
    "Black Power Salute, John Dominis, 1968",
    "Soweto Uprising, Sam Nzima, 1976",
    "The Horse In Motion, Eadweard Muybridge, 1878",
    "Abraham Lincoln, Mathew Brady, 1860",
    "Iraqi Girl At Checkpoint, Chris Hondros, 2005",
    "Gorilla In The Congo, Brent Stirton, 2007",
    "Bandit's Roost, Mulberry Street, Jacob Riis, Circa 1888",
    "Milk Drop Coronet, Harold Edgerton, 1957",
    "Surfing Hippos, Michael Nichols, 2000",
    "Moonlight: The Pond, Edward Steichen, 1904",
    "The Vanishing Race, Edward S. Curtis, 1904",
    "Betty Grable, Frank Powolny, 1943",
    "Case Study House No. 22, Los Angeles, Julius Shulman, 1960",
    "99 Cent, Andreas Gursky, 1999",
    "Blind, Paul Strand, 1916",
    "The Loch Ness Monster, 1934",
    "Windblown Jackie, Ron Galella, 1971",
    "The Hooded Man, Sergeant Ivan Frederick, 2003",
    "American Gothic, Gordon Parks, 1942",
    "Invasion Of Prague, Josef Koudelka, 1968",
    "Bosnia, Ron Haviv, 1992",
    "Boulevard Du Temple, Louis Daguerre, 1839",
    "The Dead Of Antietam, Alexander Gardner, 1862",
    "Winston Churchill, Yousuf Karsh, 1941",
    "Munich Massacre, Kurt Strumpf, 1972",
    "JFK Assassination, Frame 313, Abraham Zapruder, 1963",
    "Kent State Shootings, John Paul Filo, 1970",
    "The Falling Soldier, Robert Capa, 1936",
    "Grief, Dmitri Baltermants, 1942",
    "Birmingham, Alabama, Charles Moore, 1963",
    "Camelot, Hy Peskin, 1953",
    "The Babe Bows Out, Nat Fein, 1948",
    "Country Doctor, W. Eugene Smith, 1948",
    "Boat Of No Smiles, Eddie Adams, 1977",
    "Firing Squad In Iran, Jahangir Razmi, 1979",
    "Coffin Ban, Tami Silicio, 2004",
    "Dovima With Elephants, Paris, August, Richard Avedon, 1955",
    "Michael Jordan, Co Rentmeester, 1984",
    "The Death Of Neda, 2009",
    "The Valley Of The Shadow Of Death, Roger Fenton, 1855",
    "The Steerage, Alfred Stieglitz, 1907",
    "Trolley To New Orleans, Robert Frank, 1955",
    "Behind The Gare Saint-Lazare, Henri Cartier-Bresson, 1932",
    "Couple In Raccoon Coats, James Vanderzee, 1932",
    "Androgyny (6 Men + 6 Women), Nancy Burson, 1982",
    "Untitled (Cowboy), Richard Prince, 1989",
    "Bricklayer, August Sander, 1928",
    "The Hague, Erich Salomon, 1930",
    "Fort Peck Dam, Margaret Bourke-White, 1936",
    "Untitled Film Still 21, Cindy Sherman, 1978",
    "Brian Ridley And Lyle Heeter, Robert Mapplethorpe, 1979",
    "Demi Moore, Annie Leibovitz, 1991",
    "Cathedral Rock, Yosemite, Carleton Watkins, 1861",
    "Allende's Last Stand, Luis Orlando Lagos, 1973",
    "Molotov Man, Susan Meiselas, 1979",
    "North Korea, David Guttenfelder, 2013",
    "The Critic, Weegee, 1943",
    "Chairman Mao Swims In The Yangtze, 1966",
    "Immersions (Piss Christ), Andres Serrano, 1987",
    "Oscars Selfie, Bradley Cooper, 2014",
]


famous_operas = [
    "L'Orfeo",
    "Dido and Aeneas",
    "Giulio Cesare (Julius Caesar)",
    "Serse (Xerxes)",
    "Orfeo ed Euridice (Orpheus and Eurydice)",
    "Idomeneo",
    "Le Nozze di Figaro (The Marriage of Figaro)",
    "Die Zauberflöte (The Magic Flute)",
    "Il Barbiere di Siviglia (The Barber of Seville)",
    "Guillaume Tell (William Tell)",
    "Norma",
    "L'Elisir d'Amore (The Elixir of Love)",
    "Lucia di Lammermoor",
    "Rigoletto",
    "La Traviata",
    "Don Carlos/ Don Carlo",
    "Falstaff",
    "Pagliacci",
    "La Bohème",
    "Tosca",
    "Madama Butterfly",
    "Turandot",
    "Fidelio",
    "Der Freischütz",
    "Lohengrin",
    "Tristan und Isolde",
    "Die Meistersinger von Nürnberg",
    "Der Ring des Nibelungen",
    "Die Lustige Witwe (The Merry Widow)",
    "Salome",
    "Der Rosenkavalier",
    "Les Troyens",
    "Carmen",
    "Manon",
    "Pelléas et Mélisande",
    "The Bartered Bride",
    "Boris Godunov",
    "Eugene Onegin",
    "The Queen of&nbsp;Spades",
    "Lady Macbeth of&nbsp;Mtsensk",
    "War and Peace",
    "The Rake's Progress",
    "Jenůfa",
    "Bluebeard's Castle",
    "Wozzeck",
    "Porgy and Bess",
    "Peter Grimes",
    "The Turn of the&nbsp;Screw",
    "King Priam",
    "Le Grand Macabre",
]


famous_movies = [
    "2001: A Space Odyssey (1968)",
    "The Godfather (1972)",
    "Citizen Kane (1941)",
    "Jeanne Dielman, 23, Quai du Commerce, 1080 Bruxelles (1975)",
    "Raiders of the Lost Ark (1981)",
    "La Dolce Vita (1960)",
    "Seven Samurai (1954)",
    "In the Mood for Love (2000)",
    "There Will Be Blood (2007)",
    "Singin’ in the Rain (1952)",
    "Goodfellas (1990)",
    "North by Northwest (1959)",
    "Mulholland Drive (2001)",
    "Bicycle Thieves (1948)",
    "The Dark Knight (2008)",
    "City Lights (1931)",
    "Grand Illusion (1937)",
    "His Girl Friday (1940)",
    "The Red Shoes (1948)",
    "Vertigo (1958)",
    "Beau Travail (1999)",
    "The Searchers (1956)",
    "Persona (1966)",
    "Do the Right Thing (1989)",
    "Rashomon (1950)",
    "The Rules of the Game (1939)",
    "Jaws (1975)",
    "Double Indemnity (1944)",
    "The 400 Blows (1959)",
    "Star Wars (1977)",
    "The Passion of Joan of Arc (1928)",
    "Once Upon a Time in the West (1968)",
    "Alien (1979)",
    "Tokyo Story (1951)",
    "Pulp Fiction (1994)",
    "The Truman Show (1998)",
    "Lawrence of Arabia (1962)",
    "Psycho (1960)",
    "Sansho the Bailiff (1954)",
    "Andrei Rublev (1966)",
    "The Umbrellas of Cherbourg (1964)",
    "Chinatown (1974)",
    "The Seventh Seal (1957)",
    "Lost in Translation (2003)",
    "Taxi Driver (1976)",
    "Spirited Away (2001)",
    "Night of the Living Dead (1968)",
    "Battleship Potemkin (1925)",
    "Modern Times (1936)",
    "Breathless (1960)",
    "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964)",
    "M (1931)",
    "Blade Runner (1982)",
    "The Bitter Tears of Petra von Kant (1972)",
    "Rome, Open City (1945)",
    "Nosferatu (1922)",
    "Airplane! (1980)",
    "Under the Skin (2013)",
    "Mad Max: Fury Road (2015)",
    "Apocalypse Now (1979)",
    "Brokeback Mountain (2005)",
    "Duck Soup (1933)",
    "The Blair Witch Project (1999)",
    "All the President’s Men (1976)",
    "The Apu trilogy (1955, 1956, 1959)",
    "The General (1926)",
    "Eternal Sunshine of the Spotless Mind (2004)",
    "The Texas Chain Saw Massacre (1974)",
    "Come and See (1985)",
    "Heat (1995)",
    "The Shining (1980)",
    "Toy Story (1995)",
    "Killer of Sheep (1977)",
    "A Woman Under the Influence (1974)",
    "Annie Hall (1977)",
    "Some Like It Hot (1959)",
    "Metropolis (1927)",
    "The Maltese Falcon (1941)",
    "This Is Spinal Tap (1984)",
    "It Happened One Night (1934)",
    "Die Hard (1988)",
    "The Conformist (1970)",
    "The Thing (1982)",
    "Daughters of the Dust (1991)",
    "Barry Lyndon (1975)",
    "Raging Bull (1980)",
    "Seven (1995)",
    "Aguirre, the Wrath of God (1972)",
    "The Battle of Algiers (1966)",
    "No Country for Old Men (2007)",
    "Women on the Verge of a Nervous Breakdown (1988)",
    "The Discreet Charm of the Bourgeoisie (1972)",
    "Paths of Glory (1957)",
    "Secrets & Lies (1996)",
    "Sweet Smell of Success (1957)",
    "The Cabinet of Dr. Caligari (1920)",
    "Nashville (1975)",
    "Don’t Look Now (1973)",
    "Bonnie and Clyde (1967)",
    "Get Out (2017)",
    "Check out the best movies of all time as chosen by actors",
]


classical_music = [
    "Edvard Grieg – Peer Gynt Suite No. 1 Op. 46: Morning Mood",
    'Ludwig van Beethoven – Symphony No. 5 in C minor, Op. 67, "Fate": I. Allegro con brio',
    'Antonio Vivaldi – The Four Seasons, Op. 8, "Spring": Allegro',
    "Samuel Barber – Adagio for Strings",
    "Richard Wagner – The Valkyrie: Ride of the Valkyries",
    "Frédéric Chopin – Nocturne No. 2 in E-Flat major, Op. 9",
    "Johann Pachelbel – Canon in D Major",
    "Carl Orff – Carmina Burana: O fortuna",
    "Johann Sebastian Bach – Orchestral Suite No. 3 in D major, BWV 1068: Air",
    "Gustav Holst – The Planets, Op. 32: Jupiter, the Bringer of Jollity",
    "Claude Debussy – Suite bergamasque, L 75: Clair de lune",
    "Giuseppe Verdi – Nabucco: Chorus of the Hebrew Slaves (Va, pensiero, sull'ali dorate)",
    "Wolfgang Amadeus Mozart – Piano Concerto No. 21 in C major, K. 467: II. Andante",
    "Johann Sebastian Bach – Brandenburg Concerto No. 3 in G major, BWV 1048: Allegro",
    "Jules Massenet – Thaïs: Meditation",
    'Antonín Dvořák – Symphony No. 9 in E minor, Op. 95, "From the New World": II. Largo',
    "Johann Strauss II – On the Beautiful Blue Danube, Op. 314",
    "Johannes Brahms – Hungarian Dance No. 5 in G minor",
    "Pyotr Ilyich Tchaikovsky – Swan Lake Suite, Op. 20: Scene",
    "Erik Satie – Gymnopédie No. 1",
    "Wolfgang Amadeus Mozart – Requiem, K. 626: Lacrimosa Dies illa",
    'Ludwig van Beethoven – Bagatelle in A minor, Wo Op. 59, "Für Elise"',
    "Edward Elgar – Pomp and Circumstance, Op. 39: Land of Hope and Glory",
    "Georges Bizet – Carmen Suite No. 2: Habanera",
    'Ludwig van Beethoven – Symphony No. 9 in D minor, Op. 125, "Choral": Ode an die Freude',
    "Jacques Offenbach – The Tales of Hoffmann: Barcarolle",
    "Remo Giazotto – Adagio in G minor for Strings and Organ (after T. Albinoni)",
    'Wolfgang Amadeus Mozart – Serenade No. 13 in G major, K. 525, "Eine kleine Nachtmusik": I. Allegro',
    "Gioachino Rossini – The Barber of Seville: Overture",
    'Ludwig van Beethoven – Piano Sonata No. 14 in C-sharp minor, Op. 27:2, "Moonlight Sonata": Adagio sostenuto',
    "Bedřich Smetana – Má Vlast (My Fatherland): Vltava (The Moldau River)",
    "Luigi Boccherini – String Quintet in E major, Op. 13: Minuet (mislabeled – should be Op. 11, No. 5 (G. 275): Minuet)",
    "Wolfgang Amadeus Mozart – Symphony No. 40 in G minor, K. 550: I. Allegro Molto",
    "Antonín Dvořák – Slavonic Dance No. 2, Op. 72",
    "Charles Gounod – Ave Maria (after J.S. Bach)",
    "Jean Sibelius – Finlandia, Op. 26",
    "Wolfgang Amadeus Mozart – Piano Sonata No. 11 in A major, K. 331: Rondo alla turca",
    "Wolfgang Amadeus Mozart – The Magic Flute, K. 620: Overture",
    "George Frideric Handel – The Messiah, HWV 56: Hallelujah Chorus",
    "Edvard Grieg – Peer Gynt Suite No. 1, Op. 46: In the Hall of the Mountain King",
    "Gabriel Fauré – Pavane",
    "Johann Sebastian Bach – Double Concerto in D minor for Two Violins, BWV 1043: Vivace",
    "Georges Bizet – L'Arlésienne Suite No. 1: Prelude",
    "Johann Strauss I – Radetzky March, Op. 228",
    "Ludwig van Beethoven – Egmont, Op. 84: Overture",
    "Stanley Myers – Cavatina",
    'Arcangelo Corelli – Concerto Grosso No. 8 in G minor, Op. 6: "Christmas Concerto": Allegro',
    "Sergei Rachmaninoff – Vocalise, Op. 34",
    "Giuseppe Verdi – Messa da Requiem: Dies irae – Tuba mirum",
    "Gustav Mahler – Symphony No. 5 in C-sharp minor: Adagietto",
]

basic_art_types = [
    "Oil Painting" "Watercolor Painting",
    "Acrylic Painting",
    "Digital Painting",
    "Portrait Painting",
    "Landscape Painting",
    "Abstract Painting",
    "Impressionist Painting",
    "Realistic Painting",
    "Cubist Painting",
    "Surrealist Painting",
    "Pop Art",
    "Minimalism",
    "Contemporary Art",
    "Street Art",
    "Graffiti Art",
    "Installation Art",
    "Sculpture",
    "Ceramic Art",
    "Pottery",
    "Glassblowing",
    "Mosaic Art",
    "Woodcarving",
    "Stone Sculpture",
    "Metal Sculpture",
    "Mixed Media Art",
    "Collage Art",
    "Printmaking",
    "Etching",
    "Lithography",
    "Woodcut Print",
    "Screenprinting",
    "Photography",
    "Portrait Photography",
    "Landscape Photography",
    "Wildlife Photography",
    "Fashion Photography",
    "Fine Art Photography",
    "Still Life Photography",
    "Street Photography",
    "Documentary Photography",
    "Digital Photography",
    "Macro Photography",
    "Aerial Photography",
    "Underwater Photography",
    "Abstract Photography",
    "Astrophotography",
    "Architecture Photography",
    "Food Photography",
    "Nude Photography",
    "Black and White Photography",
    "Color Photography",
    "Polaroid Photography",
    "Polaroid Transfers",
    "Cyanotype Printing",
    "Daguerreotype",
    "Tintype Photography",
    "Pinhole Photography",
    "Photogram",
    "Photo Manipulation",
    "Collodion Process",
    "Calligraphy",
    "Hand Lettering",
    "Typography",
    "Illuminated Manuscripts",
    "Chinese Brush Painting",
    "Japanese Sumi-e",
    "Indian Miniature Painting",
    "Persian Miniature Painting",
    "Calligraffiti",
    "Bookbinding",
    "Papercraft",
    "Origami",
    "Quilling",
    "Kirigami",
    "Stained Glass",
    "Batik Art",
    "Textile Art",
    "Embroidery",
    "Weaving",
    "Tapestry",
    "Macramé",
    "Knitting",
    "Crochet",
    "Fiber Art",
    "Beadwork",
    "Leatherworking",
    "Metalwork",
    "Jewelry Design",
    "Enamel Art",
    "Digital Art",
    "3D Modeling",
    "Animation",
    "Concept Art",
    "Virtual Reality Art",
    "Augmented Reality Art",
    "Generative Art",
    "Fractal Art",
    "Kinetic Art",
    "Sound Art",
    "Interactive Art",
    "Video Art",
    "Performance Art",
    "Body Art",
    "Land Art",
    "Environmental Art",
    "Op Art",
    "Kinetic Sculpture",
    "Optical Illusions",
    "Video Game Art",
    "Character Design",
    "Conceptual Art",
    "Folk Art",
    "Outsider Art",
    "Naïve Art",
    "Graffiti Mural",
    "Public Art",
    "Digital Collage",
    "Street Installation",
    "Found Object Art",
    "Neo-Expressionism",
    "Hyperrealism",
    "Photorealism",
    "Abstract Expressionism",
    "Fauvism",
    "Pointillism",
    "Art Nouveau",
    "Art Deco",
    "Renaissance Art",
    "Baroque Art",
    "Rococo Art",
    "Romanticism",
    "Neoclassicism",
    "Pre-Raphaelite Brotherhood",
    "Hudson River School",
    "Abstract Impressionism",
    "Symbolism",
    "Dadaism",
    "Constructivism",
    "De Stijl",
    "Suprematism",
    "Abstract Geometric Art",
    "Abstract Color Field",
    "Opulent Art",
    "Action Painting",
    "Tonalism",
    "Surrealism",
    "Magic Realism",
    "Visionary Art",
    "Psychedelic Art",
    "Afrofuturism",
    "Digital Collage Art",
    "Ethereal Art",
    "Cyberpunk Art",
    "Environmental Sculpture",
    "Ceramic Sculpture",
    "Graffiti Sculpture",
    "Kinetic Installation",
    "Video Installation",
    "Digital Installation",
    "Bio Art",
    "Body Painting",
    "Holographic Art",
    "Sand Art",
    "Ice Sculpture",
    "Fruit Carving",
    "Light Painting",
    "Neon Art",
    "Bio-Design Art",
    "Textile Sculpture",
    "Glass Sculpture",
    "Landscaping Art",
    "Chalk Art",
    "Paper Sculpture",
    "Environmental Installation",
    "Interactive Sculpture",
    "Architectural Sculpture",
    "Neon Sculpture",
    "Sound Installation",
    "Site-Specific Art",
    "Subversive Art",
    "Algorithmic Art",
    "Data Visualization Art",
    "Cybernetic Art",
    "Virtual Installation",
    "Internet Art",
    "Video Game Installation",
    "Projection Mapping",
    "3D Printing Art",
    "Robotic Art",
    "Light Sculpture",
    "Fire Sculpture",
    "Smoke Art",
    "Pyrography",
    "Encaustic Painting",
    "Fireworks Art",
    "Body Casting",
    "Geode Art",
    "Microscopic Art",
    "Chiaroscuro Drawing",
]

unique_art_types = [
    "Decoupage",
    "Assemblage Art",
    "Doll Making",
    "Puppetry",
    "Marionette Theater",
    "Ventriloquism",
    "Automata Art",
    "Clockmaking Art",
    "Kinetic Sculpture",
    "Street Performance Art",
    "Living Statue Performance",
    "Body Casting Art",
    "Graffiti Calligraphy",
    "Glassblowing Sculpture",
    "Neon Sign Art",
    "Public Installation Art",
    "Ice Sculpting",
    "Balloon Sculpting",
    "Edible Art",
    "Food Carving",
    "Miniature Painting",
    "Traditional Chinese Painting",
    "Traditional Japanese Painting",
    "Plein Air Painting",
    "Pastel Painting",
    "Gouache Painting",
    "Casein Painting",
    "Fresco Painting",
    "Egg Tempera Painting",
    "Ink Wash Painting",
    "Fresco Secco",
    "Fresco Buono",
    "Fresco Mezzo",
    "Encaustic Sculpture",
    "Repoussé and Chasing",
    "Bronze Casting",
    "Lost-Wax Casting",
    "Relief Sculpture",
    "Relief Carving",
    "Scratchboard Art",
    "Scratch Art",
    "Chalk Pastel Art",
    "Chalkboard Art",
    "Street Chalk Art",
    "Chalk Mural Art",
    "Chalk Typography",
    "Chalk Stippling",
    "Eggshell Art",
    "Button Art",
    "Bead Embroidery",
    "Torn Paper Collage",
    "Glass Fusion Art",
    "Glass Painting",
    "Stained Glass Mosaic",
    "Kaleidoscope Art",
    "Light Projection Art",
    "Fire Dancing",
    "Fire Poi Art",
    "Fire Juggling",
    "Fire Staff Spinning",
    "Fire Breathing",
    "Fire Eating",
    "Fire Fan Dancing",
    "Fire Hooping",
    "Fire Levitation Wand",
    "Fire Devil Sticks",
    "Fire Hula Hoop",
    "Fire Contact Staff",
    "Fire Rope Dart",
    "Fire Meteor Dart",
    "Fire Sword Swallowing",
    "Fire Whip Cracking",
    "Fire Bed of Nails",
    "Firewalking Art",
    "Ice Carving",
    "Ice Sculpture Installation",
    "Ice Projection Mapping",
    "Ice Festival Art",
    "Ice Hotel Design",
    "Chocolate Sculpture",
    "Sand Sculpture Competition",
    "Sandcastle Art",
    "Snow Sculpture",
    "Snow Art",
    "Snow Graffiti",
    "Pumpkin Carving",
    "Fruit Sculpture",
    "Vegetable Carving",
    "Seashell Art",
    "Driftwood Art",
    "Leaf Art",
    "Coffee Painting",
    "Tea Bag Art",
    "Wine Cork Art",
    "Matchstick Art",
    "Toothpick Sculpture",
    "Nail Art",
    "String Art",
    "Noodle Art",
    "Tofu Art",
    "Digital Collage Animation",
    "Pixel Art",
    "ASCII Art",
    "Emoji Art",
    "Algorithmic Generative Art",
    "DNA Art",
    "Sound Sculpture",
]

professional_art_types = [
    "Graphic Design",
    "Web Design",
    "User Interface (UI) Design",
    "User Experience (UX) Design",
    "Logo Design",
    "Brand Identity Design",
    "Packaging Design",
    "Advertising Design",
    "Print Design",
    "Motion Graphics Design",
    "Illustration",
    "Digital Illustration",
    "Editorial Illustration",
    "Children's Book Illustration",
    "Medical Illustration",
    "Scientific Illustration",
    "Technical Illustration",
    "Architectural Illustration",
    "Fashion Illustration",
    "Concept Art for Video Games",
    "Concept Art for Animation",
    "Concept Art for Films",
    "Storyboarding",
    "Comics and Graphic Novels",
    "2D Animation",
    "3D Animation",
    "Character Animation",
    "Visual Effects (VFX)",
    "Game Design",
    "Game Development",
    "Game Art",
    "Virtual Reality (VR) Design",
    "Augmented Reality (AR) Design",
    "Virtual Set Design",
    "Film Production Design",
    "Set Decoration",
    "Costume Design",
    "Makeup Artistry for Film",
    "Photography",
    "Portrait Photography",
    "Wedding Photography",
    "Commercial Photography",
    "Product Photography",
    "Food Photography",
    "Architectural Photography",
    "Interior Design Photography",
    "Travel Photography",
    "Event Photography",
    "Fashion Photography",
    "Advertising Photography",
    "Automotive Photography",
    "Aerial Photography",
    "Underwater Photography",
    "Wildlife Photography",
    "Fine Art Photography",
    "Photojournalism",
    "Documentary Photography",
    "Sports Photography",
    "Nature Photography",
    "Pet Photography",
    "Stock Photography",
    "Music Photography",
    "Automotive Design",
    "Industrial Design",
    "Interior Design",
    "Furniture Design",
    "Exhibition Design",
    "Retail Design",
    "Event Design",
    "Textile Design",
    "Jewelry Design",
    "Fashion Design",
    "Costume Design for Theater",
    "Costume Design for Dance",
    "Costume Design for Opera",
    "Textile Production",
    "Printmaking for Fabric",
    "Tailoring",
    "Pattern Making",
    "Fashion Styling",
    "Personal Styling",
    "Wardrobe Consulting",
    "Costume Coordination for Film",
    "Costume Coordination for Theater",
    "Costume Coordination for TV",
    "Art Direction",
    "Creative Direction",
    "Visual Merchandising",
    "Exhibition Curation",
    "Museum Curation",
    "Art Gallery Management",
    "Art Restoration",
    "Art Appraisal",
    "Art Authentication",
    "Art Conservation",
    "Art Education",
    "Art Therapy",
    "Art Teaching",
    "Art History Research",
    "Art Criticism",
    "Art Writing",
    "Art Sales",
    "Art Marketing",
    "Art Consulting",
    "Art Investment",
]

# Science
science_fields = [
    "Computational Fluid Dynamics",
    "Analytic Number Theory",
    "Control Systems Engineering",
    "String Topology",
    "Genetic Epidemiology",
    "Theoretical Ecology",
    "Quantum Field Theory",
    "Industrial Engineering",
    "Quantum Gravity",
    "Crystallography",
    "Bioinformatics Algorithms",
    "Quantum Materials Science",
    "Fluid-Structure Interaction",
    "Homological Algebra",
    "Environmental Chemistry",
    "Mathematical Physics",
    "Quantum Cryptography",
    "Renewable Energy Engineering",
    "Geophysical Fluid Dynamics",
    "Molecular Modeling",
    "Algebraic Geometry",
    "Quantum Information Theory",
    "Robotics Kinematics",
    "Aerospace Materials Science",
    "Magnetic Resonance Imaging (MRI)",
    "Chemical Engineering Thermodynamics",
    "Number Theory Algorithms",
    "Structural Mechanics",
    "Nuclear Magnetic Resonance (NMR)",
    "Biomedical Informatics",
    "Quantum Algorithms",
    "Materials Engineering",
    "Quantum Chaos",
    "Supramolecular Chemistry",
    "Mathematical Optimization",
    "Environmental Engineering",
    "Quantum Chemistry Simulations",
    "Aeroelasticity",
    "Algebraic Combinatorics",
    "Chemical Process Engineering",
    "Quantum Topology",
    "Computational Molecular Biology",
    "Fluidic Nanotechnology",
    "Algebraic K-Theory",
    "Green Chemistry",
    "Mathematical Finance",
    "Quantum Robotics",
    "Geotechnical Geophysics",
    "Particle Physics Phenomenology",
    "Quantum Metrology",
    "Quantum Dot Electronics",
    "Chemical Thermodynamics",
    "Computational Quantum Chemistry",
    "Structural Analysis",
    "Nuclear Reactor Engineering",
    "Biomedical Imaging",
    "Quantum Mechanics of Solids",
    "Environmental Modeling",
    "Quantum Error Correction",
    "Fluid Flow Simulations",
    "Algebraic Number Theory Cryptography",
    "Synthetic Biology",
    "Quantum Transport Phenomena",
    "Industrial Automation",
    "Quantum Field Theory Renormalization",
    "Computational Materials Science",
    "Structural Health Monitoring",
    "Nuclear Fusion Engineering",
    "Biomechatronics",
    "Mathematical Epidemiology",
    "Quantum Biology",
    "Nanomaterials",
    "Chemical Kinetics Modeling",
    "Computational Fluidic Dynamics",
    "Algebraic Topology Techniques",
    "Quantum Neural Networks",
    "Environmental Geophysics",
    "Quantum Materials Synthesis",
    "Molecular Dynamics Simulations",
    "Finite Element Analysis",
    "Nuclear Waste Management",
    "Biomedical Signal Processing",
    "Quantum Computing Hardware",
    "Supersymmetry",
    "Chemical Reaction Engineering",
    "Computational Quantum Information",
    "Fluid-Structure Interaction Analysis",
    "Algebraic Geometry Applications",
    "Quantum Teleportation",
    "Computational Quantum Algorithms",
    "Quantum Spintronics",
    "Environmental Remediation",
    "Quantum Optomechanics",
    "Nanoscale Engineering",
    "Mathematical Biology Modeling",
    "Quantum Chemistry Methods",
    "Structural Optimization",
    "Nuclear Medicine",
    "Biomedical Data Analysis",
    "Quantum Internet",
]

more_science_fields = [
    "Lattice QCD (Quantum Chromodynamics)",
    "Fluid-Particle Interaction Modeling",
    "Hyperbolic Partial Differential Equations",
    "Cryogenic Engineering",
    "Algebraic Topology Homotopy",
    "Single-Molecule Biophysics",
    "Computational Astrophysical Magnetohydrodynamics",
    "Quantum Plasmonics",
    "Biochemical Pathway Analysis",
    "Quantum Phase Transitions",
    "Structural Vibration Analysis",
    "Nuclear Fuel Cycle Analysis",
    "Computational Quantum Optics",
    "Quantum Cosmology",
    "Microfluidics and Lab-on-a-Chip",
    "Algebraic Coding Theory",
    "Chemical Process Simulation",
    "Quantum Simulation of Condensed Matter",
    "Aerospace Propulsion Systems",
    "High-Performance Computing in Materials Science",
    "Quantum Chemical Kinetics",
    "Numerical Weather Prediction",
    "Algebraic Geometry of Moduli Spaces",
    "Computational Population Genetics",
    "Quantum Game Theory",
    "Biomechanical Modeling of Soft Tissues",
    "Computational Plasma Astrophysics",
    "Quantum Reservoir Computing",
    "Computational Electrochemistry",
    "Quantum Hall Effect",
    "Structural Health Monitoring in Civil Engineering",
    "Nuclear Fuel Cycle Analysis",
    "Computational Metabolomics",
    "Quantum Thermoelectrics",
    "Nonlinear Control Systems",
    "Quantum Robotics Control",
    "Bioinformatics Sequence Alignment",
    "Quantum Circuit Design",
    "Environmental Impact Assessment",
    "Quantum Spin Liquids",
    "Algebraic Number Theory Applications",
    "Chemical Reaction Network Theory",
    "Computational Quantum Chemistry Software",
    "Quantum Materials Characterization",
    "Structural Dynamics of Bridges",
    "Nuclear Waste Disposal Geology",
    "Biomedical Image Registration",
    "Quantum Communication Protocols",
    "Computational Plasma Chemistry",
    "Algebraic Topology in Data Analysis",
    "Quantum Dot Solar Cells",
    "Computational Bioinformatics Algorithms",
    "Fluid-Structure Interaction in Biological Systems",
    "Quantum Error Correction Codes",
    "Geotechnical Engineering Soil Dynamics",
    "Nuclear Fusion Plasma Diagnostics",
    "Quantum Machine Learning",
    "Algebraic Combinatorial Designs",
    "Chemical Process Optimization",
    "Quantum Magnetometry",
    "Computational Seismology",
    "Quantum Photonic Devices",
    "Environmental Microbiology",
    "Quantum Error Correction Schemes",
    "Mathematical Epidemiology Modeling",
    "Quantum Cryptanalysis",
    "Nanomaterials Fabrication Techniques",
    "Chemical Reaction Network Analysis",
    "Computational Quantum Field Theory",
    "Structural Engineering Seismic Design",
    "Nuclear Reactor Fuel Analysis",
    "Biomedical Signal Processing Algorithms",
    "Quantum Information Security",
    "Fluid Dynamics of Blood Flow",
    "Algebraic Coding for Data Compression",
    "Quantum Chaos Theory",
    "Computational Quantum Biology",
    "Structural Materials Testing",
    "Nuclear Fusion Reactor Design",
    "Biomedical Data Mining",
    "Quantum Entanglement Engineering",
    "Algebraic Topology in Neuroscience",
    "Chemical Process Safety Analysis",
    "Quantum Many-Body Theory",
    "Computational Environmental Modeling",
    "Quantum Algorithms for Optimization",
    "Fluid Mechanics of Respiratory Systems",
    "Algebraic Cryptanalysis",
    "Nuclear Reactor Control Systems",
    "Biomedical Image Segmentation",
    "Quantum Photonic Integrated Circuits",
    "Structural Health Monitoring in Aerospace",
    "Computational Quantum Chemistry Algorithms",
    "Quantum Error Correction Hardware",
    "Environmental Impact Assessment Modeling",
    "Quantum Information Theory Applications",
    "Algebraic Geometry in Cryptography",
    "Chemical Process Hazard Analysis",
    "Quantum Materials Synthesis Techniques",
    "Structural Engineering Rehabilitation",
]

geometric_physics_fields = [
    "Geometric Phase",
    "Yang-Mills Theory",
    "Gauge Symmetry",
    "Yangian Symmetry",
    "Geometric Algebra",
    "Wu-Yang Monopole",
    "Chern-Simons Gauge Theory",
    "Geometric Quantization",
    "Non-Abelian Geometry",
    "Twistor Theory",
    "Geometric Invariance",
    "Kaluza-Klein Theory",
    "Geometric Langlands Program",
    "Wu-Yang Monopole in Cosmology",
    "Symplectic Geometry in Quantum Mechanics",
    "Geometric Structures in General Relativity",
    "Geometric Phases in Quantum Mechanics",
    "Noncommutative Geometry in String Theory",
    "Yang-Mills-Higgs Theory",
    "Geometrically Engineered Quantum States",
    "Supersymmetric Geometry",
    "Yang-Baxter Equation",
    "Geometric Entanglement",
    "Wu-Yang Monopole in Particle Physics",
    "Geometric Quantization of Black Holes",
    "Gauge-Gravity Duality",
    "Geometric Tensor Calculus",
    "Geometric Aspects of Loop Quantum Gravity",
    "Wu-Yang Monopole in Condensed Matter Physics",
    "Geometrically Induced Topological Phases",
    "Non-Abelian Berry Phases",
    "Geometrically Enhanced Topological Insulators",
    "Yang-Mills Instantons",
    "Geometric Algebra Applications in Physics",
    "Geometric Interpretation of Quantum Field Theory",
    "Geometric Topology in Quantum Mechanics",
    "Geometric Approach to Quantum Hall Effect",
    "Geometric Anomalies in Field Theory",
    "Geometric Symmetry Breaking",
    "Geometric Mechanics in Cosmology",
    "Geometric Description of Quantum Spacetime",
    "Noncommutative Geometry in Quantum Hall Effect",
    "Geometric Properties of String Worldsheets",
    "Geometric Quantization of Moduli Spaces",
    "Yang-Baxterization",
    "Geometrically Inspired Quantum Algorithms",
    "Geometric Perspective on Quantum Information",
    "Geometric Symmetry in Quantum Optics",
    "Geometrically Engineered Quantum Materials",
    "Geometric Principles in Supersymmetry Breaking",
    "Geometric Algebra in Quantum Computing",
    "Geometric Phases in Quantum Computing",
    "Geometrically Induced Topological Defects",
    "Geometric Interpretation of Quantum Entanglement",
    "Geometric Aspects of Quantum Tomography",
    "Geometric Invariants in Quantum Field Theory",
    "Geometrically Inspired Quantum Chaos",
    "Yang-Baxterization in Quantum Computing",
    "Geometric Description of Quantum Phase Transitions",
    "Geometric Topology in Condensed Matter Physics",
    "Geometric Symmetry Breaking in Quantum Hall Systems",
    "Geometric Mechanics in Quantum Gravity",
    "Geometric Quantization of Symplectic Manifolds",
    "Geometric Phases in Yang-Mills-Higgs Theory",
    "Geometrically Enhanced Topological Phases",
    "Geometric Algebra Applications in String Theory",
    "Geometric Interpretation of Non-Abelian Gauge Theories",
    "Geometric Aspects of Twistor Theory",
    "Geometrically Induced Yangian Symmetry",
    "Wu-Yang Monopole in Quantum Chromodynamics",
]

quantum_physics_fields = [
    "Quantum Electrodynamics (QED)",
    "Quantum Chromodynamics (QCD)",
    "Supersymmetry (SUSY)",
    "String Theory",
    "General Relativity",
    "Quantum Gravity",
    "Dark Matter Physics",
    "Dark Energy Theory",
    "Quantum Field Theory (QFT)",
    "Cosmological Inflation",
    "Grand Unified Theories (GUTs)",
    "Loop Quantum Gravity",
    "Quantum Information Theory",
    "Holographic Principle",
    "Topological Quantum Field Theory",
    "Conformal Field Theory",
    "Black Hole Thermodynamics",
    "Quantum Foam",
    "Superstring Theory",
    "Noncommutative Geometry",
    "Brane World Cosmology",
    "Neutrino Physics",
    "Quantum Spin Liquids",
    "AdS/CFT Correspondence",
    "Quantum Hall Effect",
    "Topological Insulators",
    "Adiabatic Quantum Computing",
    "M-Theory",
    "Cosmic Strings",
    "Hawking Radiation",
    "Quantum Chromodynamics at Finite Temperature",
    "Axion Physics",
    "De Broglie-Bohm Pilot-Wave Theory",
    "Causal Set Theory",
    "Lattice Gauge Theory",
    "Quantum Critical Phenomena",
    "Quantum Entanglement",
    "Quantum Vacuum Fluctuations",
    "Twistors",
    "Fractional Quantum Hall Effect",
    "Ising Model",
    "Topological Superconductors",
    "Quantum Simulators",
    "Large Extra Dimensions",
    "Quantum Error Correction",
    "Quantum Many-Body Systems",
    "CP Violation",
    "Quantum Thermodynamics",
    "Soliton Physics",
    "Vacuum Energy",
    "Quantum Measurement Problem",
    "Quantum Optomechanics",
    "Quantum Phase Transitions",
    "Holonomy in Quantum Mechanics",
    "Berry Phases",
    "Fractional Statistics",
    "Quantum Walks",
    "Quantum Cellular Automata",
    "Instantons",
    "Quantum Hall Ferromagnetism",
    "AdS/Condensed Matter Correspondence",
    "Quantum Field Theory in Curved Spacetime",
    "Spintronics",
    "Quantum Monte Carlo Methods",
    "Quantum Anomalies",
    "Weyl Semimetals",
    "Quantum Quenches",
    "Superfluidity",
    "Aharonov-Bohm Effect",
    "Geometric Phases",
    "Spin Glasses",
    "Quantum Chaos",
    "Quantum Dot Arrays",
    "Kondo Effect",
    "Quantum Tomography",
    "Quantum Neural Networks",
    "Quantum Cellular Automata",
    "Fractional Quantum Mechanics",
    "Quantum Harmonic Oscillators",
    "Quantum Dots in Solids",
    "Quantum Hall Bilayers",
    "Anyons",
    "Quantum Field Theory on Noncommutative Spaces",
    "Higgs Mechanism",
    "Quantum Circuit Complexity",
    "Quantum Pseudodifferential Operators",
    "Quantum Hall Skyrmions",
    "Twisted Quantum Field Theory",
    "Toda Quantum Chains",
    "Quantum Error-Detection Codes",
    "Quantum Search Algorithms",
    "Chern-Simons Theory",
    "Quantum Computing Architectures",
    "Quantum Magnetism",
    "Quantum Chaos in Cold Atoms",
    "Quantum Mechanics of Superconductors",
    "Quantum Hall Interferometry",
    "Quantum Annealing",
    "Quantum Cellular Automata",
    "Quantum Hall Bilayers",
]

theoretical_physics_math_geometry = [
    "Differential Geometry in General Relativity",
    "Lie Groups in Yang-Mills Theory",
    "Riemannian Manifolds in Gauge Symmetry",
    "Algebraic Geometry in String Theory",
    "Symplectic Geometry in Hamiltonian Mechanics",
    "Topological Knot Theory in Chern-Simons Theory",
    "Geometric Quantization of Symplectic Manifolds",
    "Noncommutative Geometry in Quantum Mechanics",
    "Yang-Baxter Equations and Quantum Entanglement",
    "Geometric Algebra in Quantum Field Theory",
    "Lie Algebras in Supersymmetry",
    "Complex Manifolds in Twistor Theory",
    "Topological Invariants in Geometric Phases",
    "Homotopy Theory in String Theory",
    "Geometric Structures in General Relativity",
    "K-Theory in Geometric Quantization",
    "Homological Algebra in Non-Abelian Geometry",
    "Geometric Analysis in Yang-Mills-Higgs Theory",
    "Cohomology Theory in Symmetry Breaking",
    "Algebraic Topology in Quantum Mechanics",
    "Spinors in Geometric Description of Spacetime",
    "Kac-Moody Algebras in Yangian Symmetry",
    "Tensors in Geometric Interpretation of Quantum Field Theory",
    "Geometric Topology in Condensed Matter Physics",
    "Algebraic Curves in Algebraic Geometry Applications",
    "Dirac Operators in Noncommutative Geometry",
    "Morse Theory in Quantum Hall Effect",
    "Fibrations in Geometric Mechanics",
    "Calabi-Yau Manifolds in String Worldsheets",
    "Cohomological Field Theory in Topological Insulators",
    "Symplectic Reduction in Geometrically Induced Topological Phases",
    "Lie Superalgebras in Supersymmetric Geometry",
    "Homological Mirror Symmetry",
    "Connection Forms in Yang-Baxterization",
    "Symmetric Spaces in Geometrically Inspired Quantum Algorithms",
    "Kaehler Manifolds in Geometric Symmetry Breaking",
    "Algebraic Number Theory in Geometric Mechanics",
    "Atiyah-Singer Index Theorem in Geometric Quantization",
    "Cobordism Theory in Geometric Description of Quantum Phase Transitions",
    "Noncommutative Geometry in Geometric Symmetry Breaking",
    "Algebraic Cycles in Geometric Algebra Applications",
    "Symplectic Geometry in Geometrically Enhanced Topological Phases",
    "Kahler Forms in Geometric Algebra in Quantum Computing",
    "Homotopy Groups in Geometric Phases in Quantum Computing",
    "Calabi-Yau Compactification in Geometrically Induced Topological Defects",
    "Cohomological Flux Compactification",
    "Twisted K-Theory in Geometric Interpretation of Quantum Entanglement",
    "Dirac-Ramond Operators in Geometric Aspects of Quantum Tomography",
    "Morse-Novikov Theory in Geometric Invariants in Quantum Field Theory",
    "Loop Spaces in Geometrically Inspired Quantum Chaos",
    "Kaehler-Einstein Metrics in Yang-Baxterization in Quantum Computing",
    "Homotopy Quantum Field Theory",
    "Spinor Bundles in Geometric Interpretation of Non-Abelian Gauge Theories",
    "Algebraic Stacks in Geometric Aspects of Twistor Theory",
    "Cohomological Field Theory in Geometrically Induced Yangian Symmetry",
    "Symplectic Vortices in Wu-Yang Monopole in Quantum Chromodynamics",
]

theoretical_physics_math_geometry = [
    "Differential Geometry in General Relativity",
    "Lie Groups in Yang-Mills Theory",
    "Riemannian Manifolds in Gauge Symmetry",
    "Algebraic Geometry in String Theory",
    "Symplectic Geometry in Hamiltonian Mechanics",
    "Topological Knot Theory in Chern-Simons Theory",
    "Geometric Quantization of Symplectic Manifolds",
    "Noncommutative Geometry in Quantum Mechanics",
    "Yang-Baxter Equations and Quantum Entanglement",
    "Geometric Algebra in Quantum Field Theory",
    "Lie Algebras in Supersymmetry",
    "Complex Manifolds in Twistor Theory",
    "Topological Invariants in Geometric Phases",
    "Homotopy Theory in String Theory",
    "Geometric Structures in General Relativity",
    "K-Theory in Geometric Quantization",
    "Homological Algebra in Non-Abelian Geometry",
    "Geometric Analysis in Yang-Mills-Higgs Theory",
    "Cohomology Theory in Symmetry Breaking",
    "Algebraic Topology in Quantum Mechanics",
    "Spinors in Geometric Description of Spacetime",
    "Kac-Moody Algebras in Yangian Symmetry",
    "Tensors in Geometric Interpretation of Quantum Field Theory",
    "Geometric Topology in Condensed Matter Physics",
    "Algebraic Curves in Algebraic Geometry Applications",
    "Dirac Operators in Noncommutative Geometry",
    "Morse Theory in Quantum Hall Effect",
    "Fibrations in Geometric Mechanics",
    "Calabi-Yau Manifolds in String Worldsheets",
    "Cohomological Field Theory in Topological Insulators",
    "Symplectic Reduction in Geometrically Induced Topological Phases",
    "Lie Superalgebras in Supersymmetric Geometry",
    "Homological Mirror Symmetry",
    "Connection Forms in Yang-Baxterization",
    "Symmetric Spaces in Geometrically Inspired Quantum Algorithms",
    "Kaehler Manifolds in Geometric Symmetry Breaking",
    "Algebraic Number Theory in Geometric Mechanics",
    "Atiyah-Singer Index Theorem in Geometric Quantization",
    "Cobordism Theory in Geometric Description of Quantum Phase Transitions",
    "Noncommutative Geometry in Geometric Symmetry Breaking",
    "Algebraic Cycles in Geometric Algebra Applications",
    "Symplectic Geometry in Geometrically Enhanced Topological Phases",
    "Kahler Forms in Geometric Algebra in Quantum Computing",
    "Homotopy Groups in Geometric Phases in Quantum Computing",
    "Calabi-Yau Compactification in Geometrically Induced Topological Defects",
    "Cohomological Flux Compactification",
    "Twisted K-Theory in Geometric Interpretation of Quantum Entanglement",
    "Dirac-Ramond Operators in Geometric Aspects of Quantum Tomography",
    "Morse-Novikov Theory in Geometric Invariants in Quantum Field Theory",
    "Loop Spaces in Geometrically Inspired Quantum Chaos",
    "Kaehler-Einstein Metrics in Yang-Baxterization in Quantum Computing",
    "Homotopy Quantum Field Theory",
    "Spinor Bundles in Geometric Interpretation of Non-Abelian Gauge Theories",
    "Algebraic Stacks in Geometric Aspects of Twistor Theory",
    "Cohomological Field Theory in Geometrically Induced Yangian Symmetry",
    "Symplectic Vortices in Wu-Yang Monopole in Quantum Chromodynamics",
]


# Art
all_artworks = (
    famous_paintings + famous_photos + famous_operas + famous_movies + classical_music
)
all_art_fields = professional_art_types + unique_art_types + basic_art_types

# Science

all_science_fields = science_fields + more_science_fields

all_geometry_fields = theoretical_physics_math_geometry + geometric_physics_fields
all_physics_fields = (
    quantum_physics_fields
    + theoretical_physics_math_geometry
    + geometric_physics_fields
)
